name: nlp_env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.9.1=h7bae524_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_1
  - blas=1.0=openblas
  - bleach=6.2.0=py311hca03da5_0
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.8.3=py311hca03da5_0
  - cffi=1.17.1=py311h3eb5a62_1
  - click=8.1.8=py311hca03da5_0
  - cloudpickle=3.0.0=py311hca03da5_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.13.6=h3818c69_3
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py311hca03da5_0
  - expat=2.6.4=h286801f_0
  - ffmpeg=7.1.1=gpl_h193d876_101
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h1d14073_0
  - fribidi=1.0.10=h27ca646_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.13=hebf3989_1003
  - h11=0.14.0=py311hca03da5_0
  - harfbuzz=10.4.0=hb72c1af_0
  - icu=75.1=hfee45f7_0
  - ipykernel=6.29.5=py311hca03da5_1
  - jedi=0.19.2=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.4.2=py311hca03da5_0
  - jsonschema=4.23.0=py311hca03da5_0
  - jupyter_client=8.6.3=py311hca03da5_0
  - jupyter_core=5.7.2=py311hca03da5_0
  - jupyter_events=0.12.0=py311hca03da5_0
  - jupyter_server=2.15.0=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab_pygments=0.3.0=py311hca03da5_0
  - jupyterlab_server=2.27.3=py311hca03da5_0
  - kiwisolver=1.4.8=py311h313beb8_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libass=0.17.3=h16a287c_1
  - libcxx=20.1.1=ha82da77_0
  - libdeflate=1.23=hec38601_0
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.82.2=hdff4504_1
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=hfe07756_1
  - libintl=0.23.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libllvm15=15.0.7=h4429f82_5
  - liblzma=5.6.4=h39f12f2_0
  - libogg=1.3.5=h99b78c6_0
  - libopenblas=0.3.30=hf2bb037_0
  - libopenvino=2025.0.0=h3f17238_3
  - libopenvino-arm-cpu-plugin=2025.0.0=h3f17238_3
  - libopenvino-auto-batch-plugin=2025.0.0=h7f72211_3
  - libopenvino-auto-plugin=2025.0.0=h7f72211_3
  - libopenvino-hetero-plugin=2025.0.0=h718ad69_3
  - libopenvino-ir-frontend=2025.0.0=h718ad69_3
  - libopenvino-onnx-frontend=2025.0.0=h1ae5b81_3
  - libopenvino-paddle-frontend=2025.0.0=h1ae5b81_3
  - libopenvino-pytorch-frontend=2025.0.0=h286801f_3
  - libopenvino-tensorflow-frontend=2025.0.0=heb6e3e1_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h286801f_3
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.47=h3783ad8_0
  - libprotobuf=5.29.3=hccd9074_0
  - librsvg=2.58.4=h266df6f_2
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.45.2=h091b4b1_0
  - libtiff=4.7.0=h551f018_3
  - libusb=1.0.28=h5505292_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.6=h178c5d8_0
  - libzlib=1.3.1=h8359307_2
  - littleutils=0.2.4=pyhd8ed1ab_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - llvmlite=0.44.0=py311h313beb8_0
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib-base=3.10.0=py311h7ef442a_0
  - mpmath=1.3.0=py311hca03da5_0
  - nbclient=0.10.2=py311hca03da5_0
  - nbconvert-core=7.16.6=py311hca03da5_0
  - nbformat=5.10.4=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - nltk=3.9.1=py311hca03da5_0
  - notebook-shim=0.2.4=py311hca03da5_0
  - numba=0.61.0=py311h313beb8_1
  - numexpr=2.10.1=py311h5d9532f_0
  - numpy=2.1.3=py311he598dae_0
  - numpy-base=2.1.3=py311hfbfe69c_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openpyxl=3.1.5=py311h80987f9_0
  - openssl=3.4.1=h81ee809_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - packaging=24.2=py311hca03da5_0
  - pandas=2.2.3=py311hcf29cfe_0
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - pango=1.56.3=h73f1e88_0
  - parso=0.8.4=py311hca03da5_0
  - patsy=1.0.1=py311hca03da5_0
  - pcre2=10.44=h297a79d_2
  - pillow=11.1.0=py311hb9ba9e9_0
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=25.0=py311hca03da5_0
  - pixman=0.44.2=h2f9eb0b_0
  - prometheus_client=0.21.0=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pydub=0.25.1=pyhd8ed1ab_1
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.8=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.20.0=py311hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=5_cp311
  - pyyaml=6.0.2=py311h80987f9_0
  - readline=8.2=h1a28f6b_0
  - regex=2024.11.6=py311h80987f9_0
  - requests=2.32.3=py311hca03da5_1
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - scikit-learn=1.6.1=py311h313beb8_0
  - sdl2=2.32.50=h994913f_1
  - sdl3=3.2.8=he842692_0
  - seaborn=0.13.2=py311hca03da5_2
  - setuptools=72.1.0=py311hca03da5_0
  - shap=0.47.2=py311h9fa7488_0
  - slicer=0.0.8=py311h1e82210_1
  - snappy=1.2.1=h98b9ce2_1
  - sqlite=3.45.2=hf2abe2d_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py311h12bd487_0
  - svt-av1=3.0.1=h8ab69cd_0
  - tabulate=0.9.0=py311hca03da5_0
  - tbb=2021.13.0=h8149167_1
  - tinycss2=1.4.0=py311hca03da5_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.2=py311h80987f9_0
  - tqdm=4.67.1=py311hb6e6a13_0
  - traitlets=5.14.3=py311hca03da5_0
  - typing-extensions=4.12.2=py311hca03da5_0
  - typing_extensions=4.12.2=py311hca03da5_0
  - unicodedata2=15.1.0=py311h80987f9_1
  - urllib3=2.3.0=py311hca03da5_0
  - webrtcvad=2.0.10=py311h2c37856_5
  - websocket-client=1.8.0=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xarray=2025.4.0=py311hca03da5_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - audeer==2.2.1
      - audformat==1.3.1
      - audinterface==1.2.3
      - audiofile==1.5.1
      - audioread==3.0.1
      - audmath==1.4.1
      - audobject==0.7.11
      - audresample==1.3.3
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - blis==1.2.0
      - catalogue==2.0.10
      - charset-normalizer==3.4.1
      - cloudpathlib==0.21.0
      - comm==0.2.2
      - confection==0.1.5
      - cycler==0.12.1
      - cymem==2.0.11
      - debugpy==1.8.13
      - decorator==5.2.1
      - emoji==2.14.1
      - en-core-web-sm==3.8.0
      - eng-to-ipa==0.0.2
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.56.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - iso3166==2.1.1
      - iso639-lang==2.6.0
      - isoduration==20.11.0
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter-lsp==2.2.5
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - msgpack==1.1.0
      - murmurhash==1.0.12
      - networkx==3.4.2
      - notebook==7.3.3
      - opensmile==2.5.1
      - overrides==7.7.0
      - oyaml==1.0
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - praat-parselmouth==0.4.5
      - preshed==3.0.9
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==6.30.1
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-json-logger==3.3.0
      - pytz==2025.1
      - pyzmq==26.3.0
      - referencing==0.36.2
      - rich==13.9.4
      - rpds-py==0.23.1
      - scipy==1.15.2
      - send2trash==1.8.3
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - stanza==1.10.1
      - sympy==1.13.1
      - terminado==0.18.1
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - wrapt==1.17.2
      - zipp==3.21.0
prefix: /opt/anaconda3/envs/nlp_env
