name: nlp_env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.9.0
  - aom=3.6.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - comm=0.2.2
  - contourpy=1.3.1
  - dav1d=1.2.1
  - decorator=5.2.1
  - defusedxml=0.7.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - expat=2.6.4
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.10.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.8
  - lame=3.100
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpng=1.6.39
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - littleutils=0.2.4
  - llvm-openmp=14.0.6
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mpmath=1.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nltk=3.9.1
  - notebook=7.3.3
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numexpr=2.10.1
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.1
  - outdated=0.2.2
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandas-flavor=0.8.1
  - pango=1.50.7
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pingouin=0.5.5
  - pip=25.0
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-tzdata=2025.2
  - pytz=2025.1
  - pyyaml=6.0.2
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - seaborn=0.13.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - shap=0.47.2
  - six=1.17.0
  - slicer=0.0.8
  - sniffio=1.3.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tabulate=0.9.0
  - tbb=2021.8.0
  - terminado=0.18.1
  - tesseract=5.2.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xarray=2025.10.1
  - xlrd=2.0.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - audeer==2.2.2
      - audformat==1.3.2
      - audinterface==1.3.1
      - audiofile==1.5.1
      - audioread==3.0.1
      - audmath==1.4.2
      - audobject==0.7.12
      - audresample==1.3.4
      - blis==1.2.0
      - catalogue==2.0.10
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - cycler==0.12.1
      - cymem==2.0.11
      - debugpy==1.8.13
      - emoji==2.14.1
      - en-core-web-sm==3.8.0
      - eng-to-ipa==0.0.2
      - executing==2.2.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - iso3166==2.1.1
      - iso639-lang==2.6.3
      - jsonpointer==3.0.0
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - msgpack==1.1.0
      - murmurhash==1.0.12
      - networkx==3.4.2
      - opensmile==2.6.0
      - oyaml==1.0
      - pandocfilters==1.5.1
      - pooch==1.8.2
      - praat-parselmouth==0.4.5
      - preshed==3.0.9
      - protobuf==6.30.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - python-json-logger==3.3.0
      - pyzmq==26.3.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shellingham==1.5.4
      - smart-open==7.1.0
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stanza==1.10.1
      - sympy==1.13.1
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - typer==0.15.2
      - tzdata==2025.1
      - wasabi==1.1.3
      - weasel==0.4.1
      - webrtcvad==2.0.10
      - wrapt==1.17.2
