name: nlp_env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.18.4
  - dav1d=1.2.1
  - dbus=1.13.6
  - et_xmlfile=1.1.0
  - expat=2.6.4
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - graphite2=1.3.13
  - harfbuzz=10.4.0
  - icu=75.1
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20250127.1
  - libass=0.17.3
  - libcxx=20.1.1
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.4
  - libglib=2.82.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.0
  - liblzma=5.6.4
  - libogg=1.3.5
  - libopenvino=2025.0.0
  - libopenvino-arm-cpu-plugin=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.3.1
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsqlite=3.45.2
  - libtiff=4.7.0
  - libusb=1.0.28
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxml2=2.13.6
  - libzlib=1.3.1
  - ncurses=6.4
  - openh264=2.6.0
  - openpyxl=3.1.5
  - openssl=3.4.1
  - pango=1.56.3
  - pcre2=10.44
  - pip=25.0
  - pixman=0.44.2
  - pugixml=1.15
  - python=3.11.8
  - readline=8.2
  - sdl2=2.32.50
  - sdl3=3.2.8
  - setuptools=75.8.0
  - snappy=1.2.1
  - sqlite=3.45.2
  - svt-av1=3.0.1
  - tbb=2022.0.0
  - tk=8.6.13
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - audioread==3.0.1
      - blis==1.2.0
      - catalogue==2.0.10
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - cymem==2.0.11
      - decorator==5.2.1
      - emoji==2.14.1
      - en-core-web-sm==3.8.0
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - murmurhash==1.0.12
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - praat-parselmouth==0.4.5
      - preshed==3.0.9
      - protobuf==6.30.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - rich==13.9.4
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stanza==1.10.1
      - sympy==1.13.1
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - tqdm==4.67.1
      - typer==0.15.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - webrtcvad==2.0.10
      - wrapt==1.17.2
prefix: /opt/anaconda3/envs/nlp_env
